#!/bin/bash

for arg in "$@"
do
    if [ "$arg" == "--help" ] || [ "$arg" == "-h" ]
    then
	echo "BASH SEARCH BY FIZZZGEN"
	echo "-------------------------------------------------------------------"
        echo "first argument: string to search"
	echo "second argument: search limit (default 10)"
	echo "third argument: number of lines near result line to show (default 0)"
	echo "-------------------------------------------------------------------"

    exit
    fi
done

cat ~/.bash_history | rg -m ${2:-10} -C ${3:-0} "$1"
